default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: announcebot-dev

test:
  <<: *default
  database: announcebot-test

production:
  <<: *default
  database: production
